apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeName: kubemaster.example.com
      securityContext:
        fsGroup: 1000 
        runAsUser: 0
      volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: {{ .Values.pvc }}
      containers:
      - name: jenkins
        image: {{ .Values.imagename }}
        ports:
          - name: http-port
            containerPort: {{ .Values.port.cport }}
          - name: jnlp-port
            containerPort: {{ .Values.port.jport }}
        volumeMounts:
          - name: mypd
            mountPath: /var/jenkins_home
